name: release

on:
 workflow_call:
    inputs:
      version:
        type: string
        description: 'The version to release'
        required: true
 workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'The version to release'
        required: true

jobs:
  publish:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - uses: actions/checkout@v4
      - uses: coursier/cache-action@v6.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: publish in docker hub
        run: |-
          echo "$TOKEN" | gh auth login --with-token

          docker build -t mulatinho/sfm:1.0.$GITHUB_RUN_NUMBER .
          docker tag mulatinho/sfm:1.0.$GITHUB_RUN_NUMBER mulatinho/sfm:latest
          docker push mulatinho/sfm:1.0.$GITHUB_RUN_NUMBER
          docker push mulatinho/sfm:latest

          docker run -d --name sfm mulatinho/sfm sleep 5
          docker cp sfm:/usr/src/sfm/src/sfm ./sfm

          gh release create "$VERSION" --generate-notes './sfm#Linux 64bit binary'
        env:
          TOKEN: ${{ secrets.PAT_GITHUB }}
          VERSION: ${{ inputs.version }}
